### ISSUE TITLE
Error on backend

### ISSUE THREAD

**Issue by Inrego** [mmcc-xx/BirdCAGE#18] opened 2023-05-25 17:32 UTC
Hi. I've set up the containers, and configured 2 camera streams. However, nothing seems to be happening. I've restarted the containers after configuration to no avail. In the backend, I see an error:

```
2023-05-25T10:37:23.241605221Z Starting API Server
2023-05-25T10:37:23.241661045Z Starting celery_worker
2023-05-25T10:37:23.241701984Z Sleeping indefinitely
2023-05-25T10:37:23.336256582Z [2023-05-25 12:37:23 +0200] [6] [INFO] Starting gunicorn 20.1.0
2023-05-25T10:37:23.336269325Z [2023-05-25 12:37:23 +0200] [6] [INFO] Listening at: http://0.0.0.0:7007 (6)
2023-05-25T10:37:23.336271695Z [2023-05-25 12:37:23 +0200] [6] [INFO] Using worker: sync
2023-05-25T10:37:23.339509878Z [2023-05-25 12:37:23 +0200] [17] [INFO] Booting worker with pid: 17
2023-05-25T10:37:23.817438280Z Starting celery worker in celery_worker.py
2023-05-25T10:37:24.054679750Z /usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
2023-05-25T10:37:24.054694710Z absolutely not recommended!
2023-05-25T10:37:24.054696952Z 
2023-05-25T10:37:24.054698597Z Please specify a different user using the --uid option.
2023-05-25T10:37:24.054700099Z 
2023-05-25T10:37:24.054701425Z User information: uid=0 euid=0 gid=0 egid=0
2023-05-25T10:37:24.054702844Z 
2023-05-25T10:37:24.054704172Z   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
2023-05-25T10:37:24.060113621Z  
2023-05-25T10:37:24.060117771Z  -------------- celery@birdcage_backend v5.2.7 (dawn-chorus)
2023-05-25T10:37:24.060119556Z --- ***** ----- 
2023-05-25T10:37:24.060121119Z -- ******* ---- Linux-5.19.0-42-generic-x86_64-with-glibc2.31 2023-05-25 12:37:24
2023-05-25T10:37:24.060122678Z - *** --- * --- 
2023-05-25T10:37:24.060124037Z - ** ---------- [config]
2023-05-25T10:37:24.060125439Z - ** ---------- .> app:         app:0x7f73dbc0dab0
2023-05-25T10:37:24.060127102Z - ** ---------- .> transport:   redis://redis:6379/0
2023-05-25T10:37:24.060128598Z - ** ---------- .> results:     redis://redis:6379/0
2023-05-25T10:37:24.060130072Z - *** --- * --- .> concurrency: 10 (prefork)
2023-05-25T10:37:24.060131515Z -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
2023-05-25T10:37:24.060133013Z --- ***** ----- 
2023-05-25T10:37:24.060134357Z  -------------- [queues]
2023-05-25T10:37:24.060135743Z                 .> celery           exchange=celery(direct) key=celery
2023-05-25T10:37:24.060137242Z                 
2023-05-25T10:37:24.060138785Z 
2023-05-25T10:37:24.060140145Z [tasks]
2023-05-25T10:37:24.060141513Z   . app.stream_processing.analyze_recordings
2023-05-25T10:37:24.060142894Z   . app.stream_processing.record_stream
2023-05-25T10:37:24.060144310Z   . update_birdsoftheweek_table_task
2023-05-25T10:37:24.060145693Z 
2023-05-25T10:37:24.060344298Z [2023-05-25 12:37:24,060: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
2023-05-25T10:37:24.060354765Z     The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
2023-05-25T10:37:24.060356712Z     version 6.0.0. Use the result_backend instead
2023-05-25T10:37:24.060358179Z 
2023-05-25T10:37:24.060359470Z   deprecated.warn(description=f'The {setting!r} setting',
2023-05-25T10:37:24.060360965Z 
2023-05-25T10:37:24.060362346Z [2023-05-25 12:37:24,060: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
2023-05-25T10:37:24.272962009Z [2023-05-25 12:37:24,272: INFO/MainProcess] Connected to redis://redis:6379/0
2023-05-25T10:37:24.273853769Z [2023-05-25 12:37:24,273: INFO/MainProcess] mingle: searching for neighbors
2023-05-25T10:37:24.277082360Z [2023-05-25 12:37:24,276: CRITICAL/MainProcess] Unrecoverable error: ContentDisallowed('Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)')
2023-05-25T10:37:24.277085834Z Traceback (most recent call last):
2023-05-25T10:37:24.277087760Z   File "/usr/local/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
2023-05-25T10:37:24.277101795Z     self.blueprint.start(self)
2023-05-25T10:37:24.277103279Z   File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
2023-05-25T10:37:24.277104999Z     step.start(parent)
2023-05-25T10:37:24.277106429Z   File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
2023-05-25T10:37:24.277107924Z     return self.obj.start()
2023-05-25T10:37:24.277109326Z   File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
2023-05-25T10:37:24.277110853Z     blueprint.start(self)
2023-05-25T10:37:24.277112253Z   File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
2023-05-25T10:37:24.277113762Z     step.start(parent)
2023-05-25T10:37:24.277115157Z   File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 37, in start
2023-05-25T10:37:24.277116723Z     self.sync(c)
2023-05-25T10:37:24.277118109Z   File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
2023-05-25T10:37:24.277119654Z     replies = self.send_hello(c)
2023-05-25T10:37:24.277121000Z   File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
2023-05-25T10:37:24.277122556Z     replies = inspect.hello(c.hostname, our_revoked._data) or {}
2023-05-25T10:37:24.277123944Z   File "/usr/local/lib/python3.10/site-packages/celery/app/control.py", line 389, in hello
2023-05-25T10:37:24.277125381Z     return self._request('hello', from_node=from_node, revoked=revoked)
2023-05-25T10:37:24.277126805Z   File "/usr/local/lib/python3.10/site-packages/celery/app/control.py", line 106, in _request
2023-05-25T10:37:24.277142227Z     return self._prepare(self.app.control.broadcast(
2023-05-25T10:37:24.277144190Z   File "/usr/local/lib/python3.10/site-packages/celery/app/control.py", line 741, in broadcast
2023-05-25T10:37:24.277145796Z     return self.mailbox(conn)._broadcast(
2023-05-25T10:37:24.277147207Z   File "/usr/local/lib/python3.10/site-packages/kombu/pidbox.py", line 344, in _broadcast
2023-05-25T10:37:24.277148695Z     return self._collect(reply_ticket, limit=limit,
2023-05-25T10:37:24.277150069Z   File "/usr/local/lib/python3.10/site-packages/kombu/pidbox.py", line 386, in _collect
2023-05-25T10:37:24.277151512Z     self.connection.drain_events(timeout=timeout)
2023-05-25T10:37:24.277153295Z   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 316, in drain_events
2023-05-25T10:37:24.277154923Z     return self.transport.drain_events(self.connection, **kwargs)
2023-05-25T10:37:24.277156321Z   File "/usr/local/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 971, in drain_events
2023-05-25T10:37:24.277157868Z     get(self._deliver, timeout=timeout)
2023-05-25T10:37:24.277159212Z   File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 584, in get
2023-05-25T10:37:24.277160644Z     ret = self.handle_event(fileno, event)
2023-05-25T10:37:24.277162011Z   File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 566, in handle_event
2023-05-25T10:37:24.277163443Z     return self.on_readable(fileno), self
2023-05-25T10:37:24.277164787Z   File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 562, in on_readable
2023-05-25T10:37:24.277166270Z     chan.handlers[type]()
2023-05-25T10:37:24.277167615Z   File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 967, in _brpop_read
2023-05-25T10:37:24.277169032Z     self.connection._deliver(loads(bytes_to_str(item)), dest)
2023-05-25T10:37:24.277170479Z   File "/usr/local/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 991, in _deliver
2023-05-25T10:37:24.277173133Z     callback(message)
2023-05-25T10:37:24.277174581Z   File "/usr/local/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 624, in _callback
2023-05-25T10:37:24.277176079Z     return callback(message)
2023-05-25T10:37:24.277177446Z   File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 620, in _receive_callback
2023-05-25T10:37:24.277178939Z     decoded = None if on_m else message.decode()
2023-05-25T10:37:24.277180434Z   File "/usr/local/lib/python3.10/site-packages/kombu/message.py", line 194, in decode
2023-05-25T10:37:24.277181840Z     self._decoded_cache = self._decode()
2023-05-25T10:37:24.277183208Z   File "/usr/local/lib/python3.10/site-packages/kombu/message.py", line 198, in _decode
2023-05-25T10:37:24.277184655Z     return loads(self.body, self.content_type,
2023-05-25T10:37:24.277188712Z   File "/usr/local/lib/python3.10/site-packages/kombu/serialization.py", line 242, in loads
2023-05-25T10:37:24.277190432Z     raise self._for_untrusted_content(content_type, 'untrusted')
2023-05-25T10:37:24.277191862Z kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
```

**Comment by mmcc-xx** [comment] 2023-05-25 17:57
'Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)'

I would also refuse to deserialize an untrusted pickle.

Honestly I do not know what that means. I'll look into it. In the mean time, you might try going down to 1 stream definition and starting up each layer in turn to see if you can tell where the problem is.

I talk about an approach to that here:
https://github.com/mmcc-xx/BirdCAGE/issues/13

**Comment by Inrego** [comment] 2023-05-26 05:27
It seems it was a problem with the camera configuration. Transport was set to None instead of TCP.
I had redis running already for another container. I'm not that familiar with redis, but should it be deployed per app? As in I should now have 2 redis containers running? I'm asking because in the log of birdCAGE, I am seeing some errors related to keys that are being set from the other app (paperless).

```
[2023-05-26 07:20:00,091: ERROR/MainProcess] Received unregistered task of type 'paperless_mail.tasks.process_mail_accounts'.
The message has been ignored and discarded.
Did you remember to import the module containing this task?
Or maybe you're using relative imports?
Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.
The full contents of the message body was:
b'\x80\x04\x955\x00\x00\x00\x00\x00\x00\x00)}\x94}\x94(\x8c\tcallbacks\x94N\x8c\x08errbacks\x94N\x8c\x05chain\x94N\x8c\x05chord\x94Nu\x87\x94.' (64b)
Thw full contents of the message headers:
{'lang': 'py', 'task': 'paperless_mail.tasks.process_mail_accounts', 'id': '535fa432-9ab1-43d2-9815-a946e061b54c', 'shadow': None, 'eta': None, 'expires': '2023-05-26T07:29:00.090924+02:00', 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '535fa432-9ab1-43d2-9815-a946e061b54c', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen325@paperless', 'ignore_result': False}
The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'paperless_mail.tasks.process_mail_accounts'
```
So without any knowledge of Celery or redis, I think the issue might be that both Paperless and birdCAGE are using Celery with a default `routing_key` of `celery`, which means they receive eachothers messages.. If possible, I think it'd make sense to change the routing key to something app-specific.

**Comment by mmcc-xx** [comment] 2023-05-26 14:50
I'll close this issue, though some more useful  error messages seem in order.

In your docker-compose file are you mapping redis to a port or leaving it just on the virtual network?

**Closed by mmcc-xx** 2023-05-26 14:50 UTC

**Comment by Inrego** [comment] 2023-05-26 17:40
Leaving it just on the virtual network (one that I'm using across all my docker containers).
So here's my full docker-compose for birdcage:

```
version: "2.2"
services:
  birdcage_backend:
    image: "mmcc73/birdcage_backend:latest"
    container_name: birdcage_backend
    hostname: birdcage_backend
    environment:
      DATABASE_FILE: /db/birdcage.db
      API_SERVER_PORT: 7007
      TEMP_DIR_NAME: tmp
      ANALYZE_SERVER: birdnetserver
      ANALYZE_PORT: 8080
      DETECTION_DIR_NAME: detections
      CORS_ORIGINS: my.comain
      REDIS_SERVER: redis
      REDIS_PORT: 6379
      CONCURRENCY: 10 # this many processes will get started up to handle concurrent tasks. The app needs (number of streams) + 2?
                      # I think? Maybe +3? Look, I don't really know what I'm doing here.
      JWT_SECRET_KEY: "secret" #this is used to sign tokens, so use your own Enlightenment philosopher quote
    volumes:
      - /docker-volumes/birdcage/db:/db
      - /docker-volumes/birdcage/detections:/detections
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - web
    restart: unless-stopped

  birdcage_frontend:
    image: "mmcc73/birdcage_frontend:latest"
    container_name: birdcage_frontend
    hostname: birdcage_frontend
    environment:
      API_SERVER_URL: https://backend.my.domain
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - web
    restart: unless-stopped
    depends_on:
      - birdcage_backend

  birdnetserver:
    image: mmcc73/birdnetserver:latest
    container_name: birdnetserver
    hostname: birdnetserver
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
    external: true
```

As you can see, redis is not defined here, it's in another compose. Also, I'm not exposing any ports, because I am running a reverse proxy in another compose as well, which server the backend and frontend with domains and https.

**Comment by mmcc-xx** [comment] 2023-05-26 18:32
Gotcha. I don't know the right way to get two apps to share the same redis instance. It seems to be a pretty lightweight thing, so you could run two instances if you were so inclined.
